### ISSUE TITLE
Transpose event?

### ISSUE THREAD

**Issue by filipblaauw** [tvdavies/chordprojs#1]
Hi, are you supporting some kind of transpose of the chord array in your excellent library?

Like in chord-magic, but I don't think this library supports transposing multiple chords at once.
`chordMagic.transpose(chordMagic.parse('Amaj7'), -1)`

I also tried running this:
`var $song = $(chordpro.parse(chords).render("G"));` on a song in D, and that works. Is it possible to have this render function with new value on a button click?

**Comment by ghost** [comment]
At the moment, no. But this is something that can be achieved quite easily just using chord-magic.

``` javascript
['Am', 'G', 'Em', 'C', 'D'].map(function (chord) {
  chordMagic.transpose(chordMagic.parse(chord), -1)
})
```
